server:
  port: 8086
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-pay
  swagger:
    title: "黑马商场支付服务接口文档"
    package: com.hm.mall.pay.controller
spring:
  rabbitmq:
    host: 192.168.189.188
    port: 5672
    virtual-host: /tongsw
    username: tongsw
    password: 123321
    # 会导致线程阻塞，不推荐使用重连机制
#    connection-timeout: 1s # 设置MQ的连接超时时间
#    template:
#      retry:
#        enabled: true # 开启重连机制
#        initial-interval: 1000ms # 失败后首次等待时间
#        multiplier: 1 # 失败后下次等待重连的时间倍数
#        max-attempts: 3 # 最大重试次数
    # 开启发送者确认机制
    publisher-confirm-type: correlated # 开启publisher-confirm机制，并设置confirm类型（none:不开启  simple:同步等待结果  correlated:异步回调）
    publisher-returns: true # 开启publisher-return机制
